### ISSUE TITLE
What's the difference between Rama's split and Karpathy's split?

### ISSUE THREAD

**Issue by jamiechoi1995** [ruotianluo/DiscCaptioning#16]
![图片](https://user-images.githubusercontent.com/13494034/69141284-64a9a880-0aff-11ea-82f9-944c447ca5c9.png)
In Rama's paper, they said that they use the split from Karpathy's paper,
but in your README.md you mention that it's different from standard Karpathy's split.

I wonder what's the differences between these 2 splits, thanks!

**Comment by ruotianluo** [comment]
They use what's in neuraltalk2, which is actually different from what is in karpathy's paper.
