### ISSUE TITLE
python: can't open file 'scripts/prepro_ngrams.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by SkylerZheng** [ruotianluo/DiscCaptioning#2]
To train on our own, do we have to pre-process for self-critical model? If so, I think a python file is missing here in this repo.

**Comment by ruotianluo** [comment]
I forgot to include it.

**Comment by SkylerZheng** [comment]
Is it the same as the self-critical paper? If so, I can get it from there repo.

**Comment by ruotianluo** [comment]
fixed.

**Comment by SkylerZheng** [comment]
Thanks
