### ISSUE TITLE
Traceback (most recent call last):   File "train.py", line 250, in <module>     train(opt)   File "train.py", line 163, in train     if opt.evaluation_retrieval: AttributeError: 'Namespace' object has no attribute 'evaluation_retrieval' Terminating BlobFetcher

### ISSUE THREAD

**Issue by SkylerZheng** [ruotianluo/DiscCaptioning#3]
While I was training with the command "bash run_fc_con.sh", the training was terminated because the following error:

Traceback (most recent call last):
  File "train.py", line 250, in <module>
    train(opt)
  File "train.py", line 163, in train
    if opt.evaluation_retrieval:
AttributeError: 'Namespace' object has no attribute 'evaluation_retrieval'
Terminating BlobFetcher

However, in the opt.py file, I don't see the argument of "evaluation_retrieval".

**Comment by ruotianluo** [comment]
nice catch. You can delete that if.

**Comment by SkylerZheng** [comment]
You mean we assume evaluation_retrieval = True?

**Comment by ruotianluo** [comment]
should be fixed in master.

**Comment by SkylerZheng** [comment]
problem solved!

thanks a lot
