### ISSUE TITLE
IOError: Failed to interpret file 'data/cocotalk_fc/100000.npy' as a pickle. 

### ISSUE THREAD

**Issue by dongqiaqia** [ruotianluo/DiscCaptioning#5]
Hi, ruotian. When I ran ‘bash run_fc_con.sh’, the training is terminated by the above error. 
I have checked the '100000.npy ', which is 1.8G  and cannot be loaded by numpy.  So I wonder if this file is not right.

**Comment by ruotianluo** [comment]
Did you download the preextracted features and put them in the right space!?

**Comment by ruotianluo** [comment]
Sorry, I didn't read it carefully. That looks weird to me. I will try to get back tomorrow

**Comment by dongqiaqia** [comment]
Never mind.  It' s kind of you to help.

**Comment by ruotianluo** [comment]
There's definitely something went wrong.

**Comment by ruotianluo** [comment]
Try the current one?

**Comment by dongqiaqia** [comment]
The error is solved. Thanks!!
