### ISSUE TITLE
Issues in FCModel

### ISSUE THREAD

**Issue by DanielWQZ** [ruotianluo/DiscCaptioning#8]
When I try to train the retrieval model using `bash run_fc_con.sh`, there is a problem before saving model. Actually, line 147 of FCModel.py `xt = self.new_img_embed(fc_feats[k:k+1], fc_feats_d.chunk(batch_size)[k]).expand(beam_size, self.input_encoding_size)` results in the issue, because it reminds that there is no attribute named `new_img_embed`. Also, `fc_feats_d` is an error, because the pycharm says that "Unresolved reference".

But after switching `--caption_model fc` to `--caption_model att2in2` in `run_fc_con.sh` file, the issue will be solved, so I think the inference of FC model could be wrong.

BTW, (1) when training retrieval model, why do you need to use the caption model to generate captions?
(2) the image features is extracted before training the model, so I think you do not fine-tune the CNN, right?

**Comment by ruotianluo** [comment]
what if you change that new_img_embed to img_embed

**Comment by DanielWQZ** [comment]
Thanks, Routian, I have solved the problem. 
Just change `xt = self.new_img_embed(fc_feats[k:k+1], fc_feats_d.chunk(batch_size)[k]).expand(beam_size, self.input_encoding_size)` to `xt = self.img_embed(fc_feats[k:k + 1]).expand(beam_size, self.input_encoding_size)`
