### ISSUE TITLE
Unable to download pretrained models

### ISSUE THREAD

**Issue by pxu4114** [ruotianluo/DiscCaptioning#9]
Thanks for the implementation.

I downloaded the pre-trained models but the file is not a folder which eval.sh code is asking for and the downloaded file is in a file format which is not accessible.

I think the file gets corrupted after downloading from the drive.

IOError: [Errno 20] Not a directory: 'log_att_d1/infos_att_d1.pkl'

**Comment by ruotianluo** [comment]
It's not corrupted. Did you extract to current directory or into folder log_att_d1

**Comment by ruotianluo** [comment]
Can you download log_att_d1.tar again. It's correct on my side.

**Comment by pxu4114** [comment]
Problem solved. Thank you
